proc printto log='/home/u63982087/BIOS511/Logs/lab8_730784042.log' new;run;

/************************************************************************************
   Project: BIOS 511

   Program Name: Lab8
   
   Author : Jocelyn(Zhuoya) Wang
   
   Date Created: 2024.09.18
   
   Purpose : This program is a practice of ODS SELECT & ODS EXCLUDE, ODS OUTPUT, STYLE
**************************************************************************************/
 
%put %upcase(no)TE: Program being run by 730784042;
options nofullstimer;  
 
 
libname classlib '~/my_shared_file_links/u49231441/Data' access = readonly; 
run; /*access a libref in class folder*/


/***** Question 1 *****/
ods rtf file = '/home/u63982087/BIOS511/Output/lab8_730784042.rtf' startpage = bygroup;
/* Create rtf file and splite page for each group*/

ods noproctitle;/*suppress the procedure title*/

ods select FishersExact ;/*select a specific output (the name is shown by trace)*/

/*********** Question 1 part A ***********/
title "Fisher's Table For Treatment and Statuas";
   proc freq data = classlib.living_data; /*apply proc freq to living data*/
        tables treatment*status/fisher;  /*make a fisher table*/
   run;


/*********** Question 1 part B ***********/
title "Result By Treatments";
    proc sort data = classlib.prostate out = pros; 
       by treatment; /* sort prostate data by treatment*/
    run;
    
    proc print data = pros; /*print the four variables of the data by treatement*/
       by treatment;
       var patientnumber serumhemoglobin serumpap tumorsize;
    run;
    
ods rtf close; /*close the rtf file*/
  
  
  
/***** Question 2 *****/
ods pdf file = '/home/u63982087/BIOS511/Output/lab8_730784042.pdf' style = SAPPHIRE startpage = yes;
/* create a pdf file and change the style to SAPPHIRE*/


ods exclude all; /*suppress the output generated by proc univariate*/
   proc univariate data = classlib.drivers; 
      var drivers;/*statistics for the variable 'drivers' in drivers dataset */
      ods output testsforlocation = locationtests; /*create data set for test for locatioin values*/
   run;
ods select all; /*turn output back on*/


proc print data = locationtests; /* print the dataset for test location values*/ 
  title "Test For Locations for Drivers";
run;


/******** Question 2 partE ********/

ods output summary = pros_summary; /* summary information by ods output*/
   proc means data = classlib.prostate;
      
      var serumhemoglobin; /*statistics only of the variable "serumhemoglobin" 
                             in prostate dataset*/
      
      output out = serum_output; /*output out to create a data set for the statistics */
      title "Statistics of Serumhemoglobin in Prostate Dataset";
      
   run;
ods output close; /*close the ods output*/


/******** Question 2 partF ********/

proc print data = pros_summary; 
   title "Prostate Summary by ODS Output";
run;/*print the data set created by ods output*/


proc print data = serum_output;
   title "Prostate Summary by Output Out";
run;/*print the data set created by output out*/


ods pdf close;/*close the pdf file*/

proc printto; run;
