proc printto log='/home/u63982087/BIOS511/Logs/lab9_73XXXXXX.log' new;run;

/************************************************************************************
   Project: BIOS 511

   Program Name: Lab9
   
   Author : Jocelyn(Zhuoya) Wang
   
   Date Created: 2024.09.25
   
   Purpose : This program is a practice of ODS graphic output and select desired plots
**************************************************************************************/

%put %upcase(no)TE: Program being run by 73XXXXXX;
options nofullstimer;  
 



libname classlib '~/my_shared_file_links/u49231441/Data' access = readonly; 
run; /*access a libref in class folder*/


ods pdf file = '/home/u63982087/BIOS511/Output/lab9_73XXXXXX.pdf' startpage = yes;
/* create a pdf file */


/***** Question 1 *****/
proc sort data = sashelp.bweight out = bweight;
     by visit; /*sort data by visit variable*/
run;

ods graphics on; 
ods select plots; /*only keep plot named plots generated by proc univariate*/
proc univariate data = bweight plot;
    title "Plots by Visit Type";
    by visit; /*sort the data by visit variable*/
    var weight;/*only present the weight variable as analysis variable*/
run; 


/***** Question 2 *****/
proc freq data = classlib.dm;
   title "Frequency Table & Plot";
   tables armcd*race / norow nocol plots = (freqplot(groupby = row twoway=cluster));
run;/*generate crosstabulation by armcd and race & only request frequency table */
/*frequecy plot is grouped by the armcd variables*/
   
/***** Question 3 *****/
proc freq data = classlib.depression;
    title "Agreeplot of Beddays and Acuteillness";
    tables beddays*acuteillness/ agree plots = agreeplot; 
run;/*combination of number of beddays and acute illness vairbles*/
/*agree test and only present the agreeplot*/

   
/***** Question 4 *****/
proc glm data = classlib.dmvs plots= DIAGNOSTICS;/*request diagnostic plot*/
    title "Diagnositics Plot";
    class race;/*class the data by race*/
    model cfb = race sysbp0 / solution; /*regression model*/
run;
quit;

ods pdf close;/*close the pdf file*/
proc printto; run;
